# pytorch入门学习笔记--张量

In [2]:
import torch

In [11]:
# 创建张量
x = torch.empty(3,4)#空张量
y = torch.rand(3,4,dtype=torch.float)# 随机张量，值在0，1之间,类型为float #类型有float,int,long,double等
p = torch.randn(3,4) # 标准正态分布的随机值，均值为0，方差为1
z = torch.zeros(3,4) # 零张量
n = torch.ones(3,4) # 单位张量
m = torch.tensor([2.3,4]) # 直接将数组类型变成张量类型
x,y,p,z,n,m

(tensor([[0.0000e+00, 8.7712e-01, 2.1274e+23, 3.4034e-06],
         [1.0579e+21, 5.4363e+22, 2.7301e-06, 1.3090e+22],
         [1.0533e+21, 1.7680e-04, 3.2919e-09, 6.8620e-07]]),
 tensor([[0.1493, 0.7796, 0.3621, 0.0746],
         [0.6983, 0.5425, 0.8951, 0.4312],
         [0.9196, 0.3056, 0.5086, 0.9956]]),
 tensor([[ 1.8490,  0.3377, -0.2640, -1.5079],
         [ 1.7335, -0.2648, -0.3296,  0.0636],
         [-2.5631, -0.4883,  1.7666,  1.2985]]),
 tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 tensor([2.3000, 4.0000]))

In [18]:
# 张量的基本操作
t = torch.randn_like(y,dtype=torch.float)#从已有的张量中创建一个相同维度的张量
print(t)
print(t.size()) # 张量维度
print(t[:,0]) # 取张量第一列，切片功能跟numpy相同
print("\n1x12",t.view(12))#将3*4的张量reshape成一维张量
print("\n2x6",t.view(2,6))# #将3*4的张量reshape成2*6张量
num = torch.randn(1)
print("val:",num.item(),type(num.item())) #从one element tensor中取值

tensor([[ 0.5838, -0.0833, -0.6712, -0.6246],
        [ 1.9392,  1.1987,  0.7184, -1.5299],
        [-0.4571,  0.4022, -0.1025,  1.8049]])
torch.Size([3, 4])
tensor([ 0.5838,  1.9392, -0.4571])

1x12 tensor([ 0.5838, -0.0833, -0.6712, -0.6246,  1.9392,  1.1987,  0.7184, -1.5299,
        -0.4571,  0.4022, -0.1025,  1.8049])

2x6 tensor([[ 0.5838, -0.0833, -0.6712, -0.6246,  1.9392,  1.1987],
        [ 0.7184, -1.5299, -0.4571,  0.4022, -0.1025,  1.8049]])
val: -0.41023898124694824 <class 'float'>


In [20]:
# 相同维度的张量相加（四种方法） 
print(y+t)
print(torch.add(y,t))
res = torch.empty(3,4)
torch.add(y,t,out=res)
print(res) # 将加和赋值给空张量
t.add_(y) # 直接修改t
print(t) 

tensor([[ 0.7330,  0.6962, -0.3091, -0.5500],
        [ 2.6375,  1.7412,  1.6135, -1.0987],
        [ 0.4625,  0.7078,  0.4061,  2.8005]])
tensor([[ 0.7330,  0.6962, -0.3091, -0.5500],
        [ 2.6375,  1.7412,  1.6135, -1.0987],
        [ 0.4625,  0.7078,  0.4061,  2.8005]])
tensor([[ 0.7330,  0.6962, -0.3091, -0.5500],
        [ 2.6375,  1.7412,  1.6135, -1.0987],
        [ 0.4625,  0.7078,  0.4061,  2.8005]])
tensor([[ 0.7330,  0.6962, -0.3091, -0.5500],
        [ 2.6375,  1.7412,  1.6135, -1.0987],
        [ 0.4625,  0.7078,  0.4061,  2.8005]])


In [22]:
# torch.tensor->numpy.ndarray
a = torch.ones(5) # 单元张量
b = a.numpy() # 转化成numpy中的数组类型
print(a,b,type(a),type(b))
a.add_(1) # 将张量中每个元素加1
print(a,b) # 可见b也随之加1！！！

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.] <class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]


In [23]:
# numpy.ndarray->torch.tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b,type(a),type(b))
np.add(a,1,out=a)
print(a,b)# 可见b也随之加1！！！

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64) <class 'numpy.ndarray'> <class 'torch.Tensor'>
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [34]:
# 张量的自动微分
x = torch.ones(3,4,requires_grad=True)
print(x)
y = x+2
print(y)
print(x.grad_fn,y.grad_fn) # 可见,y多了一个AddBackward 这里的x是属于用户自己定义的,而y属于函数产生的,所以y有grad_fn属性,而x没有.
z = y*y*3
out = z.mean()
print(z,out)
print(z.grad_fn) # MulBackward
print(out.grad_fn)# MeanBackward
out.backward() # 对out进行反向传播
print("d(out)/dx:",x.grad) # out关于x的梯度
# 这里的out为标量,所以直接调用backward()函数即可,一定要注意当out为数组时,用先定义一样大小的Tensor例如grad_output执行.backgrad(grad_output)语句.


tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], grad_fn=<AddBackward0>)
None <AddBackward0 object at 0x104f0db10>
tensor([[27., 27., 27., 27.],
        [27., 27., 27., 27.],
        [27., 27., 27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
d(out)/dx: tensor([[1.5000, 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000, 1.5000],
        [1.5000, 1.5000, 1.5000, 1.5000]])


In [38]:
# 创建y=x*2^n的计算过程,结果为矢量
x = torch.randn(3,requires_grad=True)
y=x*2
while y.data.norm()<1000:
    y = y*2
    print(y.data.norm)
print(y,'\n')
# 计算v=[0.1,1.0,0.0001]处的梯度
v=  torch.tensor([0.1,1.0,0.0001],dtype=torch.float)
y.backward(v)
print("y在v处的梯度",x.grad,"\n")
# 关闭梯度的功能
print(x.requires_grad)
print((x**2).requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)
# 关闭梯度的第二种方法
print(x.requires_grad)
y = x.detach() # 关闭梯度
print(x,y,y.requires_grad)
print(x.eq(y).all()) # eq()比较相等
print(x.requires_grad,y.requires_grad)

<bound method Tensor.norm of tensor([-2.7014,  3.9266, -2.4432])>
<bound method Tensor.norm of tensor([-5.4028,  7.8533, -4.8865])>
<bound method Tensor.norm of tensor([-10.8055,  15.7066,  -9.7729])>
<bound method Tensor.norm of tensor([-21.6111,  31.4131, -19.5458])>
<bound method Tensor.norm of tensor([-43.2221,  62.8262, -39.0917])>
<bound method Tensor.norm of tensor([-86.4443, 125.6524, -78.1833])>
<bound method Tensor.norm of tensor([-172.8886,  251.3049, -156.3666])>
<bound method Tensor.norm of tensor([-345.7772,  502.6097, -312.7333])>
<bound method Tensor.norm of tensor([-691.5543, 1005.2194, -625.4666])>
tensor([-691.5543, 1005.2194, -625.4666], grad_fn=<MulBackward0>) 

y在v处的梯度 tensor([1.0240e+02, 1.0240e+03, 1.0240e-01]) 

True
True
False
True
tensor([-0.6753,  0.9817, -0.6108], requires_grad=True) tensor([-0.6753,  0.9817, -0.6108]) False
tensor(True)
True False


In [41]:
# 比较tensor相等
outputs=torch.FloatTensor([[1],[2],[3]])
targets=torch.FloatTensor([[0],[2],[3]])
print(targets.eq(outputs.data))
print("相等的个数",targets.eq(outputs.data).sum()) # 统计相等的个数
# 找出tensor最大值
outputs=torch.FloatTensor([[1],[2],[3]])
print("size:",outputs,outputs.size()) 
print("column max:",torch.max(outputs.data,1)) # 第1维度的最大值以及对应indices
print("row max:",torch.max(outputs.data,0)) # 第0维度最大值以及对应indices

tensor([[False],
        [ True],
        [ True]])
相等的个数 tensor(2)
size: tensor([[1.],
        [2.],
        [3.]]) torch.Size([3, 1])
column max: torch.return_types.max(
values=tensor([1., 2., 3.]),
indices=tensor([0, 0, 0]))
row max: torch.return_types.max(
values=tensor([3.]),
indices=tensor([2]))


# pytorch入门学习笔记--神经网络

In [54]:
# 以LeNet5为例
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net,self).__init__()
        self.conv1 = nn.Conv2d(3,6,5) # 输入为32x32？？，卷积核大小为5*5，卷积核种类为6
        self.conv2 = nn.Conv2d(6,16,5) # 输入为前一层的6个特征，卷积核大小为5*5，卷积核种类为16
        self.fc1 = nn.Linear(16*5*5,120)#输入为16*5*5，输出为120
        self.fc2 = nn.Linear(120,84)# 输入为120维，输出为84维
        self.fc3 = nn.Linear(84,10) # 输入为84维，输出为10
    def forward(self,x):
        x = F.max_pool2d(F.relu(self.conv1(x)),(2,2)) # 卷积—relu-2x2下采样
        x = F.max_pool2d(F.relu(self.conv2(x)),2) # 卷积-relu-2x2下采样 # 卷积核为方形时，可只写一个维度
        x = x.view(-1,16*5*5)# flatten
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
net = Net()
print(net)

Net(
  (conv1): Conv2d(3, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear(in_features=400, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [55]:
# 打印网络参数
params = list(net.parameters())
print(len(params))
for i in range(len(params)):
    print(i,params[i].size())

10
0 torch.Size([6, 3, 5, 5])
1 torch.Size([6])
2 torch.Size([16, 6, 5, 5])
3 torch.Size([16])
4 torch.Size([120, 400])
5 torch.Size([120])
6 torch.Size([84, 120])
7 torch.Size([84])
8 torch.Size([10, 84])
9 torch.Size([10])


In [56]:
# 随机输入一个向量，查看前向传播输出
input = torch.randn(1,3,32,32)
print(input.size())
out = net(input)
print(out)

torch.Size([1, 3, 32, 32])
tensor([[-0.1136,  0.1119, -0.0774, -0.0855, -0.0064, -0.1242, -0.1182, -0.0673,
          0.0925,  0.0184]], grad_fn=<AddmmBackward>)


In [57]:
# 将梯度初始化
net.zero_grad() 
# 调用backward()函数之前都要将梯度清零，因为如果梯度不清零，pytorch中会将上次计算的梯度和本次计算的梯度累加。
# 这样逻辑的好处是，当我们的硬件限制不能使用更大的bachsize时，使用多次计算较小的bachsize的梯度平均值来代替，
# 更方便，坏处当然是每次都要清零梯度。

In [58]:
# 随机一个梯度进行反向传播
out.backward(torch.randn(1,10))

In [59]:
# loss func
mse = nn.MSELoss()

In [60]:
# 计算loss
target = torch.randn(10)
print(target)
target = target.view(1,-1) # 变成列向量
print(target)

output = net(input)
loss = mse(output,target)
print(loss)

tensor([ 1.5753,  0.0053,  1.1684, -2.1197,  0.2603, -0.7836,  0.8957,  0.9131,
         1.7946,  1.8100])
tensor([[ 1.5753,  0.0053,  1.1684, -2.1197,  0.2603, -0.7836,  0.8957,  0.9131,
          1.7946,  1.8100]])
tensor(1.7156, grad_fn=<MseLossBackward>)


In [61]:
# 将梯度初始化，计算上一步中loss的反向传播
net.zero_grad()
print("conv1.bias.grad")
print(net.conv1.bias.grad)
loss.backward()
print("conv1.bias.grad")
print(net.conv1.bias.grad) 

conv1.bias.grad
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad
tensor([ 0.0112, -0.0102,  0.0186,  0.0059, -0.0032, -0.0102])


In [62]:
# 更新权重
import torch.optim as optim
optimizer = optim.SGD(net.parameters(),lr=0.01)
# 使用优化器更新权重
optimizer.zero_grad()
output = net(input)
loss = mse(output,target)
loss.backward()
optimizer.step()

# pytorch入门学习笔记--分类器

In [63]:
# 训练一个分类器
import torchvision
import torchvision.transforms as transforms #transforms模块提供了一般的图像转换操作类
# 将（0，1）区间的数据标准化到(-1,1)
transform = transforms.Compose([transforms.ToTensor(),transforms.Normalize((0.5,0.5,0.5),(0.5,0.5,0.5))])
# transforms.ToTensor() 把shape=(H x W x C)的像素值范围为[0, 255]的PIL.Image或者numpy.ndarray转换成shape=(C x H x W)的像素值范围为[0.0, 1.0]的torch.FloatTensor。
# transforms.Normalize 此转换类作用于torch.*Tensor。给定均值(R, G, B)和标准差(R, G, B)，用公式channel = (channel - mean) / std进行规范化。

In [89]:
# 加载数据
batch_size = 32
trainset = torchvision.datasets.CIFAR10(root='/Users/yoloc/data/', train=True,download=False,transform=transform)
testset = torchvision.datasets.CIFAR10(root='/Users/yoloc/data/', train=False,download=False,transform=transform)
trainloader = torch.utils.data.DataLoader(trainset,batch_size=batch_size,shuffle=True,num_workers=2)
testloader = torch.utils.data.DataLoader(testset,batch_size=batch_size,shuffle=True,num_workers=2)
classes = ('plane','car','bird','cat','deer','dog','frog','horse','ship','truck')

In [80]:
net2=Net() # 使用前面的lenet网络
cet = nn.CrossEntropyLoss()
optimizer2= optim.SGD(net2.parameters(),lr=0.001,momentum=0.9)

In [90]:
# training
for epoch in range(5):
    running_loss = 0.0
    for i,data in enumerate(trainloader,0):
        inputs,labels=data
        optimizer2.zero_grad()
        outputs = net2(inputs) # 前馈
        loss = cet(outputs,labels)
        loss.backward()
        optimizer2.step()
        running_loss+=loss.item()
        if i%100==99:
            print('[%d,%5d] loss: %.3f' % (epoch+1,i+1,running_loss/2000))
            running_loss=0.0
print("Finished Training")

[1,  100] loss: 0.100
[1,  200] loss: 0.100
[1,  300] loss: 0.099
[1,  400] loss: 0.097
[1,  500] loss: 0.097
[1,  600] loss: 0.096
[1,  700] loss: 0.094
[1,  800] loss: 0.094
[1,  900] loss: 0.091
[1, 1000] loss: 0.092
[1, 1100] loss: 0.089
[1, 1200] loss: 0.088
[1, 1300] loss: 0.086
[1, 1400] loss: 0.088
[1, 1500] loss: 0.087
[2,  100] loss: 0.084
[2,  200] loss: 0.085
[2,  300] loss: 0.084
[2,  400] loss: 0.081
[2,  500] loss: 0.080
[2,  600] loss: 0.081
[2,  700] loss: 0.081
[2,  800] loss: 0.080
[2,  900] loss: 0.080
[2, 1000] loss: 0.079
[2, 1100] loss: 0.078
[2, 1200] loss: 0.076
[2, 1300] loss: 0.079
[2, 1400] loss: 0.077
[2, 1500] loss: 0.077
[3,  100] loss: 0.075
[3,  200] loss: 0.075
[3,  300] loss: 0.076
[3,  400] loss: 0.076
[3,  500] loss: 0.073
[3,  600] loss: 0.073
[3,  700] loss: 0.072
[3,  800] loss: 0.075
[3,  900] loss: 0.073
[3, 1000] loss: 0.074
[3, 1100] loss: 0.074
[3, 1200] loss: 0.074
[3, 1300] loss: 0.072
[3, 1400] loss: 0.072
[3, 1500] loss: 0.072
[4,  100] 

In [96]:
# 使用模型预测
%matplotlib inline
from matplotlib import pyplot as plt
dataiter = iter(testloader)
images,labels = dataiter.next()
# plt.imshow(torchvision.utils.make_grid(images))
print('GroundTruth:',' '.join('%5s' % classes[labels[j]] for j in range(4)))

GroundTruth:   car plane  ship truck


In [103]:
outputs = net2(images)
_,predicted = torch.max(outputs,1)
print('Predicted:',' '.join('%5s' % classes[predicted[j]] for j in range(4)))

Predicted:   car  bird plane truck


In [107]:
# 打分
correct = 0
total = 0
with torch.no_grad():
    for data in testloader:
        images,labels = data
        outputs = net2(images)
        _,predicted = torch.max(outputs.data,1)
        total+=labels.size(0)
        correct += (predicted==labels).sum().item()
print(correct,total)
print('acc on the %d test images: %d %%' % (total,100 * correct /total))

5232 10000
acc on the 10000 test images: 52 %


In [108]:
# 存取模型
PATH='./cifar_net.pth'
torch.save(net.state_dict(),PATH) # 保存
pretrained_net = torch.load(PATH) # 读取
net3 = Net()
net3.load_state_dict(pretrained_net) # 加载权重

<All keys matched successfully>